import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MenuBar from "@/app/components/MenuBar";
import DividerGold from "@/app/components/divider";
import { ThemeProvider } from 'next-themes'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Casamento",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
      >
        <MenuBar />
        <DividerGold />
        {children}
      </ThemeProvider>

      </body>
    </html>
  );
}
